new-plan-apply (#7)

diff --git a/.github/workflows/terraform-apply.yml b/.github/workflows/terraform-apply.yml
--- a/.github/workflows/terraform-apply.yml
+++ b/.github/workflows/terraform-apply.yml
@@ -1,73 +1,147 @@
-name: Terraform Apply
+name: 'Terraform Plan/Apply'
 
 on:
-  workflow_call:
-    inputs:
-      working-directory:
-        description: The directory of the Terraform configuration
-        type: string
-        required: true
-    secrets:
-      TF_TOKEN_APP_TERRAFORM_IO:
-        description: The Terraform Cloud API token
-        required: true
-      localAdminPassword:
-        required: true
-      domainAdminPassword:
-        required: true
-      deploymentUserPassword:
-        required: true
-      servicePrincipalSecret:
-        required: true
+  push:
+    branches:
+    - main
+  pull_request:
+    branches:
+    - main
 
+#Special permissions required for OIDC authentication
 permissions:
   id-token: write
   contents: read
+  pull-requests: write
+
+#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
+env:
+  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
+  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
+  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
+  TF_TOKEN_APP_TERRAFORM_IO: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
 
 jobs:
-  terraform-apply:
-    runs-on: terraform-cloud
-    environment: Production
+  terraform-plan:
+    name: 'Terraform Plan'
+    runs-on: ubuntu-latest
     env:
-      TF_ORGANIZATION: ${{ vars.TF_ORGANIZATION }}
-      TF_TOKEN_APP_TERRAFORM_IO: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
-      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
-      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
-      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
-      ARM_USE_OIDC: true
-      TF_VAR_subscription_id: ${{ vars.ARM_SUBSCRIPTION_ID }}
-      TF_VAR_local_admin_user: ${{ vars.localAdminUser }}
-      TF_VAR_hci_0_local_admin_user: ${{ vars.localAdminUser }}
-      TF_VAR_local_admin_password: ${{ secrets.localAdminPassword }}
-      TF_VAR_hci_0_local_admin_password: ${{ secrets.localAdminPassword }}
-      TF_VAR_domain_admin_user: ${{ vars.domainAdminUser }}
-      TF_VAR_domain_admin_password: ${{ secrets.domainAdminPassword }}
-      TF_VAR_deployment_user_password: ${{ secrets.deploymentUserPassword }}
-      TF_VAR_hci_0_deployment_user_password: ${{ secrets.deploymentUserPassword }}
-      TF_VAR_service_principal_id: ${{ vars.servicePrincipalId }}
-      TF_VAR_hci_0_service_principal_id: ${{ vars.servicePrincipalId }}
-      TF_VAR_service_principal_secret: ${{ secrets.servicePrincipalSecret }}
-      TF_VAR_hci_0_service_principal_secret: ${{ secrets.servicePrincipalSecret }}
-      TF_VAR_rp_service_principal_object_id: ${{ vars.rpServicePrincipalObjectId }}
-      TF_VAR_vm_admin_password: ${{ secrets.localAdminPassword }}
-      TF_VAR_domain_join_password: ${{ secrets.domainAdminPassword }}
+      #this is needed since we are running terraform with read-only permissions
+      ARM_SKIP_PROVIDER_REGISTRATION: true
+    outputs:
+      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
+
     steps:
-      - uses: actions/checkout@v4
+    # Checkout the repository to the GitHub Actions runner
+    - name: Checkout
+      uses: actions/checkout@v4
 
-      - uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_wrapper: false
+    # Install the latest version of the Terraform CLI
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v3
+      with:
+        terraform_wrapper: false
 
-      - uses: azure/login@v2
-        with:
-          client-id: ${{ vars.ARM_CLIENT_ID }}
-          tenant-id: ${{ vars.ARM_TENANT_ID }}
-          allow-no-subscriptions: true
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    - name: Terraform Init
+      run: terraform init
 
-      - uses: wegmans/actions/terraform/unlock-azure-resources@v1
-        with:
-          working-directory: ${{ inputs.working-directory }}
+    # Checks that all Terraform configuration files adhere to a canonical format
+    # Will fail the build if not
+    - name: Terraform Format
+      run: terraform fmt -check
 
-      - uses: wegmans/actions/terraform/apply@v1
-        with:
-          working-directory: ${{ inputs.working-directory }}
+    # Generates an execution plan for Terraform
+    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+    - name: Terraform Plan
+      id: tf-plan
+      run: |
+        export exitcode=0
+        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+
+        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+        
+        if [ $exitcode -eq 1 ]; then
+          echo Terraform Plan Failed!
+          exit 1
+        else 
+          exit 0
+        fi
+        
+    # Save plan to artifacts  
+    - name: Publish Terraform Plan
+      uses: actions/upload-artifact@v4
+      with:
+        name: tfplan
+        path: tfplan
+        
+    # Create string output of Terraform Plan
+    - name: Create String Output
+      id: tf-plan-string
+      run: |
+        TERRAFORM_PLAN=$(terraform show -no-color tfplan)
+        
+        delimiter="$(openssl rand -hex 8)"
+        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+        echo "" >> $GITHUB_OUTPUT
+        echo '```terraform' >> $GITHUB_OUTPUT
+        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
+        echo '```' >> $GITHUB_OUTPUT
+        echo "</details>" >> $GITHUB_OUTPUT
+        echo "${delimiter}" >> $GITHUB_OUTPUT
+        
+    # Publish Terraform Plan as task summary
+    - name: Publish Terraform Plan to Task Summary
+      env:
+        SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
+      run: |
+        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+      
+    # If this is a PR post the changes
+    - name: Push Terraform Output to PR
+      if: github.ref != 'refs/heads/main'
+      uses: actions/github-script@v7
+      env:
+        SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
+      with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const body = `${process.env.SUMMARY}`;
+            github.rest.issues.createComment({
+                issue_number: context.issue.number,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                body: body
+            })
+                
+  terraform-apply:
+    name: 'Terraform Apply'
+    if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.tfplanExitCode == 2
+    runs-on: ubuntu-latest
+    environment: production
+    needs: [terraform-plan]
+    
+    steps:
+    # Checkout the repository to the GitHub Actions runner
+    - name: Checkout
+      uses: actions/checkout@v4
+
+    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v3
+
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    - name: Terraform Init
+      run: terraform init
+
+    # Download saved plan from artifacts  
+    - name: Download Terraform Plan
+      uses: actions/download-artifact@v4
+      with:
+        name: tfplan
+
+    # Terraform Apply
+    - name: Terraform Apply
+      run: terraform apply -auto-approve tfplan
